// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqaY4RJZYaHLecVunCsbzL1AFZ_pDHFR4',
    appId: '1:165091924989:web:6dfce5aa481d03f9b29794',
    messagingSenderId: '165091924989',
    projectId: 'reddit-clone-3775c',
    authDomain: 'reddit-clone-3775c.firebaseapp.com',
    storageBucket: 'reddit-clone-3775c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEiQOtWzpFBFGQ5zDWpi1vFIhMTVMSSZo',
    appId: '1:165091924989:android:8e7fe131e50aebbcb29794',
    messagingSenderId: '165091924989',
    projectId: 'reddit-clone-3775c',
    storageBucket: 'reddit-clone-3775c.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBATzjD9lk0FJaajyUe01dEFQDvfVh6WLg',
    appId: '1:165091924989:ios:207566713f0b1c18b29794',
    messagingSenderId: '165091924989',
    projectId: 'reddit-clone-3775c',
    storageBucket: 'reddit-clone-3775c.appspot.com',
    iosClientId: '165091924989-p3clfhf2d8qalt5a5hqi5a0bu7c9rkq9.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditClone',
  );
}
